### ISSUE TITLE
Sprint 2 Submission [Android Bootcamp]

### ISSUE THREAD

**Issue by asweigart** [asweigart/WhipperSnapper#1]
All of the basic functionality is complete.

/cc @codepathreview @codepath

(If you want to run the actual code, set MainActivity.java's DEBUG_USE_REAL_PHONE_NUMBER to true to use your actual phone number. This was used to test as multiple users, since the user identity is automatically tied to the phone number of the device.)

Note: I've left the team with Vince and Hetang and am doing the final project on my own, which is why there is no Sprint 1 issue in this repo. Our app designs have sufficiently diverged and I've cleared this with Nathan.)

**Comment by codepathreview** [comment]
:+1: Thanks for letting me know about the update. Looks good so far.  Hope you are proud of what you have achieved in ~6 weeks.
- Consider taking actions on the review comments and please create [issues/milestones](https://github.com/asweigart/WhipperSnapper/milestones) for each of your sprint.
- Good work implementing the core flows. You have made decent progress in sprint 2 and it seems a lot of your application logic is in place.
- Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
- While working on polishing your app for next sprint, remember that your app follows the [android design guidelines](http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns](http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
